(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq-default make-backup-files nil)
(setq-default auto-save-default nil)
(setq-default truncate-lines t)
(setq-default inhibit-startup-screen t)
(setq-default inhibit-splash-screen t)
